#!/bin/sh

set -e ; cd "${0%/*}"

WEBTEMPLATER_PATH="$(realpath ./Building/site_builder/site_builder)"
CPY_PATH="$(realpath ./Building/cpy/bin/)"
ln -s "$(realpath ./Building/cpy/cpython-fork/python)" "$CPY_PATH/cpy_binary" || :
"${CPY_PATH}/cpy_binary" -m pip install -r ./requirements.txt

rm -rf ./dest || :
sh "${WEBTEMPLATER_PATH}" ./LaserProject ./dest
cd dest
clear
sh "${CPY_PATH}/cpy_tool" server.py
# sh "${CPY_PATH}/cpy_tool" -m waitress-serve --call 'flaskr:create_app'