#!/bin/sh

set -e ; cd "${0%/*}"

WEBTEMPLATER_PATH="$(realpath ./Building/site_builder/site_builder)"
CPY_PATH="$(realpath ./Building/cpy/bin/)"

rm -rf ./dest || :
sh "${WEBTEMPLATER_PATH}" ./LaserProject ./dest
cd dest
clear
sh "${CPY_PATH}/cpy" server.py